"""
Data models and constants for EcoTravel application.
"""

# Turkish cities database for geocoding fallback
TURKISH_CITIES = {
    "ankara": {"lat": 39.9334, "lng": 32.8597, "name": "Ankara"},
    "çankaya": {"lat": 39.9181, "lng": 32.8619, "name": "Çankaya, Ankara"},
    "kızılay": {"lat": 39.9191, "lng": 32.8543, "name": "Kızılay, Ankara"},
    "istanbul": {"lat": 41.0082, "lng": 28.9784, "name": "İstanbul"},
    "İstanbul": {"lat": 41.0082, "lng": 28.9784, "name": "İstanbul"},
    "beyoğlu": {"lat": 41.0370, "lng": 28.9784, "name": "Beyoğlu, İstanbul"},
    "kadıköy": {"lat": 40.9833, "lng": 29.0333, "name": "Kadıköy, İstanbul"},
    "beşiktaş": {"lat": 41.0428, "lng": 29.0078, "name": "Beşiktaş, İstanbul"},
    "izmir": {"lat": 38.4237, "lng": 27.1428, "name": "İzmir"},
    "İzmir": {"lat": 38.4237, "lng": 27.1428, "name": "İzmir"},
    "konak": {"lat": 38.4189, "lng": 27.1287, "name": "Konak, İzmir"},
    "karşıyaka": {"lat": 38.4597, "lng": 27.1142, "name": "Karşıyaka, İzmir"},
    "antalya": {"lat": 36.8969, "lng": 30.7133, "name": "Antalya"},
    "muratpaşa": {"lat": 36.8889, "lng": 30.7061, "name": "Muratpaşa, Antalya"},
    "bursa": {"lat": 40.1826, "lng": 29.0665, "name": "Bursa"},
    "osmangazi": {"lat": 40.1873, "lng": 29.0591, "name": "Osmangazi, Bursa"},
    "adana": {"lat": 37.0000, "lng": 35.3213, "name": "Adana"},
    "seyhan": {"lat": 37.0011, "lng": 35.3160, "name": "Seyhan, Adana"},
    "gaziantep": {"lat": 37.0662, "lng": 37.3833, "name": "Gaziantep"},
    "şehitkamil": {"lat": 37.0662, "lng": 37.3833, "name": "Şehitkamil, Gaziantep"},
    "konya": {"lat": 37.8746, "lng": 32.4932, "name": "Konya"},
    "meram": {"lat": 37.8706, "lng": 32.4858, "name": "Meram, Konya"},
    "kayseri": {"lat": 38.7312, "lng": 35.4787, "name": "Kayseri"},
    "melikgazi": {"lat": 38.7205, "lng": 35.4897, "name": "Melikgazi, Kayseri"},
    "eskişehir": {"lat": 39.7767, "lng": 30.5206, "name": "Eskişehir"},
    "odunpazarı": {"lat": 39.7833, "lng": 30.5333, "name": "Odunpazarı, Eskişehir"},
    "trabzon": {"lat": 41.0027, "lng": 39.7168, "name": "Trabzon"},
    "ortahisar": {"lat": 40.9939, "lng": 39.7217, "name": "Ortahisar, Trabzon"},
    "denizli": {"lat": 37.7765, "lng": 29.0864, "name": "Denizli"},
    "pamukkale": {"lat": 37.9200, "lng": 29.1200, "name": "Pamukkale, Denizli"},
    "nevşehir": {"lat": 38.6431, "lng": 34.8286, "name": "Nevşehir"},
    "kapadokya": {"lat": 38.6431, "lng": 34.8286, "name": "Kapadokya, Nevşehir"},
    "fethiye": {"lat": 36.6542, "lng": 29.1256, "name": "Fethiye"},
    "ölüdeniz": {"lat": 36.5500, "lng": 29.1167, "name": "Ölüdeniz, Fethiye"},
    "adıyaman": {"lat": 37.7648, "lng": 38.2786, "name": "Adıyaman"},
    "nemrut": {"lat": 37.9803, "lng": 38.7414, "name": "Nemrut, Adıyaman"},
}

# Sample POI data (Points of Interest) - 2026 fiyatlarıyla
POI_DATABASE = [
    # Ankara
    {
        "id": 1,
        "name": "Anıtkabir",
        "location": {"lat": 39.9250, "lng": 32.8369},
        "city": "Ankara",
        "category": "culture",
        "description": "Atatürk'ün anıt mezarı ve müzesi",
        "visit_duration": 2,
        "cost_basic": 0,
        "cost_mid": 100,
        "cost_luxury": 250,
        "rating": 4.9,
    },
    {
        "id": 2,
        "name": "Ankara Kalesi",
        "location": {"lat": 39.9392, "lng": 32.8647},
        "city": "Ankara",
        "category": "culture",
        "description": "Tarihi kale ve panoramik şehir manzarası",
        "visit_duration": 2,
        "cost_basic": 0,
        "cost_mid": 50,
        "cost_luxury": 150,
        "rating": 4.5,
    },
    {
        "id": 3,
        "name": "Anadolu Medeniyetleri Müzesi",
        "location": {"lat": 39.9402, "lng": 32.8625},
        "city": "Ankara",
        "category": "culture",
        "description": "Anadolu'nun tarihi ve arkeolojik eserleri",
        "visit_duration": 3,
        "cost_basic": 150,
        "cost_mid": 200,
        "cost_luxury": 350,
        "rating": 4.7,
    },
    # Kapadokya Bölgesi
    {
        "id": 4,
        "name": "Kapadokya Sıcak Hava Balonu",
        "location": {"lat": 38.6431, "lng": 34.8286},
        "city": "Nevşehir",
        "category": "nature",
        "description": "Eşsiz manzarada sıcak hava balonu turu",
        "visit_duration": 3,
        "cost_basic": 3500,
        "cost_mid": 5000,
        "cost_luxury": 8000,
        "rating": 4.9,
    },
    {
        "id": 5,
        "name": "Göreme Açık Hava Müzesi",
        "location": {"lat": 38.6425, "lng": 34.8284},
        "city": "Nevşehir",
        "category": "culture",
        "description": "Kayaya oyulmuş kiliseler ve freskleri",
        "visit_duration": 3,
        "cost_basic": 450,
        "cost_mid": 600,
        "cost_luxury": 900,
        "rating": 4.8,
    },
    {
        "id": 6,
        "name": "Derinkuyu Yeraltı Şehri",
        "location": {"lat": 38.3738, "lng": 34.7342},
        "city": "Nevşehir",
        "category": "culture",
        "description": "8 katlı antik yeraltı şehri",
        "visit_duration": 2,
        "cost_basic": 350,
        "cost_mid": 450,
        "cost_luxury": 700,
        "rating": 4.6,
    },
    # İstanbul
    {
        "id": 7,
        "name": "Topkapı Sarayı",
        "location": {"lat": 41.0115, "lng": 28.9833},
        "city": "İstanbul",
        "category": "culture",
        "description": "Osmanlı İmparatorluğu'nun muhteşem sarayı",
        "visit_duration": 3,
        "cost_basic": 500,
        "cost_mid": 800,
        "cost_luxury": 1500,
        "rating": 4.8,
    },
    {
        "id": 8,
        "name": "Ayasofya Camii",
        "location": {"lat": 41.0086, "lng": 28.9802},
        "city": "İstanbul",
        "category": "culture",
        "description": "1500 yıllık tarihi yapı",
        "visit_duration": 2,
        "cost_basic": 0,
        "cost_mid": 150,
        "cost_luxury": 400,
        "rating": 4.9,
    },
    {
        "id": 9,
        "name": "Boğaz Turu",
        "location": {"lat": 41.0400, "lng": 29.0050},
        "city": "İstanbul",
        "category": "nature",
        "description": "İstanbul Boğazı'nda tekne turu",
        "visit_duration": 3,
        "cost_basic": 400,
        "cost_mid": 800,
        "cost_luxury": 2000,
        "rating": 4.7,
    },
    {
        "id": 10,
        "name": "Kapalıçarşı",
        "location": {"lat": 41.0106, "lng": 28.9680},
        "city": "İstanbul",
        "category": "gastronomy",
        "description": "Tarihi kapalı çarşı ve alışveriş",
        "visit_duration": 3,
        "cost_basic": 200,
        "cost_mid": 500,
        "cost_luxury": 1500,
        "rating": 4.5,
    },
    {
        "id": 11,
        "name": "Dolmabahçe Sarayı",
        "location": {"lat": 41.0391, "lng": 29.0003},
        "city": "İstanbul",
        "category": "culture",
        "description": "Boğaz kıyısındaki görkemli saray",
        "visit_duration": 2,
        "cost_basic": 400,
        "cost_mid": 600,
        "cost_luxury": 1000,
        "rating": 4.7,
    },
    # İzmir ve Çevresi
    {
        "id": 12,
        "name": "Efes Antik Kenti",
        "location": {"lat": 37.9392, "lng": 27.3409},
        "city": "İzmir",
        "category": "culture",
        "description": "Dünyanın en iyi korunmuş antik Roma şehri",
        "visit_duration": 4,
        "cost_basic": 450,
        "cost_mid": 700,
        "cost_luxury": 1200,
        "rating": 4.9,
    },
    {
        "id": 13,
        "name": "Şirince Köyü",
        "location": {"lat": 37.9478, "lng": 27.4497},
        "city": "İzmir",
        "category": "gastronomy",
        "description": "Şarap ve geleneksel lezzetler",
        "visit_duration": 3,
        "cost_basic": 300,
        "cost_mid": 600,
        "cost_luxury": 1200,
        "rating": 4.6,
    },
    {
        "id": 14,
        "name": "Alaçatı",
        "location": {"lat": 38.2667, "lng": 26.3667},
        "city": "İzmir",
        "category": "nature",
        "description": "Rüzgar sörfü ve taş evler",
        "visit_duration": 5,
        "cost_basic": 500,
        "cost_mid": 1000,
        "cost_luxury": 2500,
        "rating": 4.7,
    },
    # Antalya
    {
        "id": 15,
        "name": "Kaleiçi",
        "location": {"lat": 36.8854, "lng": 30.7056},
        "city": "Antalya",
        "category": "culture",
        "description": "Tarihi liman ve dar sokaklar",
        "visit_duration": 3,
        "cost_basic": 0,
        "cost_mid": 200,
        "cost_luxury": 600,
        "rating": 4.6,
    },
    {
        "id": 16,
        "name": "Düden Şelalesi",
        "location": {"lat": 36.9108, "lng": 30.7614},
        "city": "Antalya",
        "category": "nature",
        "description": "Muhteşem doğal şelale",
        "visit_duration": 2,
        "cost_basic": 150,
        "cost_mid": 250,
        "cost_luxury": 500,
        "rating": 4.5,
    },
    {
        "id": 17,
        "name": "Perge Antik Kenti",
        "location": {"lat": 36.9614, "lng": 30.8522},
        "city": "Antalya",
        "category": "culture",
        "description": "Roma dönemi antik kent",
        "visit_duration": 3,
        "cost_basic": 300,
        "cost_mid": 450,
        "cost_luxury": 800,
        "rating": 4.4,
    },
    # Pamukkale
    {
        "id": 18,
        "name": "Pamukkale Travertenleri",
        "location": {"lat": 37.9200, "lng": 29.1200},
        "city": "Denizli",
        "category": "nature",
        "description": "Beyaz travertenler ve termal havuzlar",
        "visit_duration": 4,
        "cost_basic": 400,
        "cost_mid": 700,
        "cost_luxury": 1400,
        "rating": 4.8,
    },
    {
        "id": 19,
        "name": "Hierapolis Antik Kenti",
        "location": {"lat": 37.9244, "lng": 29.1258},
        "city": "Denizli",
        "category": "culture",
        "description": "Pamukkale üzerindeki antik şehir",
        "visit_duration": 2,
        "cost_basic": 200,
        "cost_mid": 350,
        "cost_luxury": 650,
        "rating": 4.6,
    },
    # Fethiye
    {
        "id": 20,
        "name": "Ölüdeniz Plajı",
        "location": {"lat": 36.5500, "lng": 29.1167},
        "city": "Fethiye",
        "category": "nature",
        "description": "Turkuaz lagün ve muhteşem plaj",
        "visit_duration": 6,
        "cost_basic": 300,
        "cost_mid": 700,
        "cost_luxury": 1800,
        "rating": 4.9,
    },
    {
        "id": 21,
        "name": "Yamaç Paraşütü (Ölüdeniz)",
        "location": {"lat": 36.5485, "lng": 29.1103},
        "city": "Fethiye",
        "category": "nature",
        "description": "Babadağ'dan yamaç paraşütü deneyimi",
        "visit_duration": 3,
        "cost_basic": 1500,
        "cost_mid": 2000,
        "cost_luxury": 3500,
        "rating": 4.9,
    },
    {
        "id": 22,
        "name": "Saklıkent Kanyonu",
        "location": {"lat": 36.4833, "lng": 29.3167},
        "city": "Fethiye",
        "category": "nature",
        "description": "18 km uzunluğunda dev kanyon",
        "visit_duration": 4,
        "cost_basic": 250,
        "cost_mid": 450,
        "cost_luxury": 900,
        "rating": 4.7,
    },
    # Konya
    {
        "id": 23,
        "name": "Mevlana Müzesi",
        "location": {"lat": 37.8712, "lng": 32.5044},
        "city": "Konya",
        "category": "culture",
        "description": "Mevlana'nın türbesi ve müzesi",
        "visit_duration": 2,
        "cost_basic": 0,
        "cost_mid": 100,
        "cost_luxury": 300,
        "rating": 4.7,
    },
    # Adıyaman
    {
        "id": 24,
        "name": "Nemrut Dağı",
        "location": {"lat": 37.9803, "lng": 38.7414},
        "city": "Adıyaman",
        "category": "nature",
        "description": "Dev heykeller ve büyüleyici gün doğumu",
        "visit_duration": 6,
        "cost_basic": 600,
        "cost_mid": 1000,
        "cost_luxury": 2000,
        "rating": 4.8,
    },
    # Bursa
    {
        "id": 25,
        "name": "Uludağ",
        "location": {"lat": 40.0969, "lng": 29.2706},
        "city": "Bursa",
        "category": "nature",
        "description": "Kayak merkezi ve teleferik",
        "visit_duration": 6,
        "cost_basic": 800,
        "cost_mid": 1500,
        "cost_luxury": 3500,
        "rating": 4.6,
    },
    {
        "id": 26,
        "name": "Bursa Ulu Cami",
        "location": {"lat": 40.1833, "lng": 29.0625},
        "city": "Bursa",
        "category": "culture",
        "description": "Osmanlı mimarisinin şaheseri",
        "visit_duration": 1,
        "cost_basic": 0,
        "cost_mid": 50,
        "cost_luxury": 150,
        "rating": 4.5,
    },
]

# Konaklama veritabanı - 2026 gerçekçi fiyatlar
ACCOMMODATION_DATABASE = [
    {
        "city": "Ankara",
        "basic": {"name": "Hostel/Pansiyon", "cost_per_night": 400},
        "mid": {"name": "3 Yıldız Otel", "cost_per_night": 1200},
        "luxury": {"name": "5 Yıldız Otel", "cost_per_night": 3500},
    },
    {
        "city": "Nevşehir",
        "basic": {"name": "Pansiyon", "cost_per_night": 600},
        "mid": {"name": "Mağara Otel", "cost_per_night": 1800},
        "luxury": {"name": "Butik Mağara Otel", "cost_per_night": 5000},
    },
    {
        "city": "İzmir",
        "basic": {"name": "Hostel", "cost_per_night": 450},
        "mid": {"name": "3 Yıldız Otel", "cost_per_night": 1400},
        "luxury": {"name": "5 Yıldız Sahil Oteli", "cost_per_night": 4500},
    },
    {
        "city": "Denizli",
        "basic": {"name": "Pansiyon", "cost_per_night": 500},
        "mid": {"name": "Termal Otel", "cost_per_night": 1500},
        "luxury": {"name": "Termal Spa Resort", "cost_per_night": 4000},
    },
    {
        "city": "İstanbul",
        "basic": {"name": "Hostel", "cost_per_night": 600},
        "mid": {"name": "Butik Otel", "cost_per_night": 2200},
        "luxury": {"name": "5 Yıldız Boğaz Oteli", "cost_per_night": 7000},
    },
    {
        "city": "Fethiye",
        "basic": {"name": "Pansiyon", "cost_per_night": 550},
        "mid": {"name": "Resort Otel", "cost_per_night": 1800},
        "luxury": {"name": "Luxury Beach Resort", "cost_per_night": 5500},
    },
    {
        "city": "Antalya",
        "basic": {"name": "Pansiyon", "cost_per_night": 550},
        "mid": {"name": "4 Yıldız Otel", "cost_per_night": 1900},
        "luxury": {"name": "5 Yıldız Ultra Her Şey Dahil", "cost_per_night": 6000},
    },
    {
        "city": "Adıyaman",
        "basic": {"name": "Otel", "cost_per_night": 400},
        "mid": {"name": "3 Yıldız Otel", "cost_per_night": 1000},
        "luxury": {"name": "Dağ Evi Resort", "cost_per_night": 2800},
    },
    {
        "city": "Konya",
        "basic": {"name": "Otel", "cost_per_night": 400},
        "mid": {"name": "3 Yıldız Otel", "cost_per_night": 1100},
        "luxury": {"name": "Lüks Otel", "cost_per_night": 3000},
    },
    {
        "city": "Bursa",
        "basic": {"name": "Pansiyon", "cost_per_night": 450},
        "mid": {"name": "3 Yıldız Otel", "cost_per_night": 1300},
        "luxury": {"name": "Termal Resort", "cost_per_night": 4000},
    },
]
